name: "@gayansandamal/ez-object-diff"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Publish to NPM
        run: npm addUser --auth-type=legacy
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
