name: Publish Package to npmjs
on:
  push:
    branches:
      - main
  # release:
  #   types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Checking out...
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - name: 🟢 Installing node...
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: 🚀 Publishing...
      - run: npm ci
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
